# Generated by Django 4.1.7 on 2026-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("short_description", models.CharField(max_length=280)),
                ("role", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("ongoing", "Ongoing"), ("completed", "Completed")],
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated technology tags, e.g. 'Django, PostgreSQL'.",
                        max_length=200,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                ("is_open_source", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-start_date", "title"],
            },
        ),
    ]
