# Generated by Django 4.1.7 on 2026-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("publication_date", models.DateField()),
                ("url", models.URLField()),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-publication_date", "title"],
            },
        ),
    ]
