# Generated by Django 4.1.7 on 2026-09-17 10:40

from django.db import migrations, models
import resume.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience", models.TextField(blank=True)),
                ("education", models.TextField(blank=True)),
                ("skills", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="resume/",
                        validators=[resume.validators.validate_pdf_file],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
